name: test_action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Hello World
        run: echo Hello, World.

      - run: echo Bye > world.txt

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: world.txt
